# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, omarchy-launch-tui yazi
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Git, exec, omarchy-launch-tui bash -lc lazygit
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- bitwarden-desktop
# add zed editor open 
bindd = SUPER SHIFT, Z, Zed Editor, exec, omarchy-launch-or-focus "^zed$" "uwsm-app -- zed"

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
# bindd = SUPER SHIFT, M, YouTube Music, exec, omarchy-launch-webapp "https://music.youtube.com/"
# bindd = SUPER SHIFT, C, Crunchyroll, exec, omarchy-launch-webapp "https://www.crunchyroll.com/"
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# move focused binding override
bind = SUPER SHIFT, h, movefocus, l
bind = SUPER SHIFT, j, movefocus, d
bind = SUPER SHIFT, k, movefocus, u
bind = SUPER SHIFT, l, movefocus, r
