# Set prefix key to Ctrl+f
unbind C-b
set-option -g prefix C-f
bind C-f send-prefix

# Minor default settings
set-option -g status-position top
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on 
set -gq allow-passthrough on
set -g visual-activity off
setw -g mode-keys vi
set -g automatic-rename off
set -g mouse on
set -g detach-on-destroy off  # don't exit from tmux when closing a session

#Keybindings
bind v copy-mode
bind c new-window
bind r command-prompt -I "#W" "rename-window '%%'"
bind d confirm-before -p "Kill window #W? (y/n)" kill-window

bind -r n next-window
bind -r p previous-window


bind x confirm-before -p "Kill pane? (y/n)" kill-pane

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel


bind-key "i" display-popup -E -w 40% "sesh connect \"$(
 sesh list -i | gum filter --limit 1 --no-sort --fuzzy --placeholder 'Pick a sesh' --height 50 --prompt='⚡'
)\""

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'Subbeh/tmux-tpad'
set -g @plugin 'laktak/extrakto'

set -g @tpad-git-bind          "C-g"
set -g @tpad-git-cmd           "lazygit"
set -g @tpad-git-per-dir       "true"
set -g @tpad-git-style         "fg=yellow"
set -g @tpad-git-width         "90%"
set -g @tpad-git-height        "90%"

set -g @tpad-docker-bind       "C-d"
set -g @tpad-docker-cmd        "lazydocker"
set -g @tpad-docker-style      "fg=cyan"
set -g @tpad-docker-width      "90%"
set -g @tpad-docker-height     "90%"

set -g @tpad-scratchpad-bind   "C-/"
set -g @tpad-scratchpad-opts "status on"
set -g @tpad-scratchpad-dir    "#{pane_current_path}"
set -g @tpad-scratchpad-width       "90%"
set -g @tpad-scratchpad-height      "90%"

set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_current_number_color "#{@thm_green}"
set -g @catppuccin_window_text "#[bold] #W "
set -g @catppuccin_window_number ""
set -g @catppuccin_window_current_text "#{?client_prefix,#[bold] #W ,#[bold] #W }"
set -g @catppuccin_window_current_number ""
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_right_separator "#[fg=#{@_ctp_status_bg},reverse]#[none]"

set -g @catppuccin_window_left_separator "#[fg=#{@_ctp_status_bg}] #[none]"
set -g @catppuccin_window_middle_separator "#[bg=#{@catppuccin_window_text_color},fg=#{@catppuccin_window_number_color}]"
set -g @catppuccin_window_current_middle_separator "#[bg=#{@catppuccin_window_current_text_color},fg=#{@catppuccin_window_current_number_color}]"

run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

set -g window-status-separator ""
set -g status-left-length 0
set -g status-left "#[fg=#{@thm_fg} bold]TMUX (#S) "
set -ga status-left "#{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_green} bold]NORMAL }}"
set -g status-right ""

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
